services:
  # Gateway - Escribe datos al smart contract
  - type: web
    name: bae-gateway
    env: rust
    plan: free
    rootDir: bae-backend
    buildCommand: cargo build --release --bin gateway
    startCommand: ./target/release/gateway
    envVars:
      - key: RUST_LOG
        value: info
      - key: MQTT_BROKER
        value: broker.hivemq.com
      - key: MQTT_PORT
        value: 1883
      - key: RPC_URL
        value: https://testnet-passet-hub-eth-rpc.polkadot.io
      - key: CONTRACT_ADDRESS
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: ENCRYPTION_KEY
        generateValue: true

  # Sensor Simulator - Genera datos de prueba
  - type: worker
    name: bae-sensor-simulator
    env: rust
    plan: free
    rootDir: bae-backend
    buildCommand: cargo build --release --bin sensor-simulator
    startCommand: ./target/release/sensor-simulator
    envVars:
      - key: RUST_LOG
        value: info
      - key: MQTT_BROKER
        value: broker.hivemq.com
      - key: MQTT_PORT
        value: 1883
      - key: DEVICE_ID
        value: ESP32-001
      - key: INTERVAL_SECS
        value: 30
